In [32]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spam-text-message-classification/SPAM text message 20170820 - Data.csv


In [33]:
df=pd.read_csv('/kaggle/input/spam-text-message-classification/SPAM text message 20170820 - Data.csv')

In [34]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

**Text cleaning**

In [35]:
import re
import nltk 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer


In [36]:
ps=PorterStemmer()
wordnet=WordNetLemmatizer()


In [37]:
collect = []
for i in range(0, len(df)):
    values = re.sub('[^a-zA-Z]', ' ', df['Message'][i])
    values = values.lower()
    values = values.split()
    values = [wordnet.lemmatize(word) for word in values if not word in stopwords.words('english')]
    values = ' '.join(values)
    collect.append(values)
    

**Bag of words**

******Convert deopendant feature ham and spam into dummies**

In [38]:
df['Category'].replace({'ham':1,'spam':0},inplace=True)

In [39]:
df['Category']

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: int64

In [40]:
y=df['Category']
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: int64

**Apply train_test_split**

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [42]:
from sklearn.svm import SVC
model=SVC()
model

SVC()

In [43]:
model.fit(X_train,y_train)

SVC()

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cs=CountVectorizer(max_features=1000)
X=cs.fit_transform(collect).toarray()

In [45]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [48]:
y_pred=model.predict(X_test)
y_pred

array([1, 0, 1, ..., 1, 1, 1])

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

0.9847533632286996


In [30]:
print(confusion_matrix(y_test,y_pred))

[[143  17]
 [  0 955]]
